name: skindetect
description: Skin Disease Detect
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1
  http: ^0.12.0
  carousel_slider: ^1.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: "assets/fonts/Montserrat-Regular.otf"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
